### ISSUE TITLE
[Feature request] UWP Support

### ISSUE THREAD

**Issue by mhrastegari** [roubachof/Sharpnado.MaterialFrame#1]
Would be nice to have it in our UWP projects :( 
plus i thing it fits perfectly with UWP because recently you provided AcrylicBlur and it's almost like the original WinUI design of it. :)

**Comment by roubachof** [comment]
done with version 1.1 :)

**Comment by MitchBomcanhao** [comment]
hey @roubachof - am I missing something here? I've tried adding MaterialFrame to my solution but it won't build on UWP if it is set to x86, only builds and runs if setting the platform to x64. 
when it fails on "x86" platform, it says that sharpnado.materialframe\1.1.1\lib\uap10.0.16299\Sharpnado.MaterialFrame.UWP.dll is built for "AMD64"

**Comment by roubachof** [comment]
Same as here https://github.com/roubachof/Sharpnado.Shadows/issues/9. If you have a solution for the nuspec...

**Comment by roubachof** [comment]
Reference: https://github.com/Cheesebaron/Nugetx86x64

Sorry I don't have time for this issue right now. But I will gladly review PRs :)

**Comment by roubachof** [comment]
The issue was created here #9
