### ISSUE TITLE
When the frames display for the first time on iOS there's a white flash as the frame appears

### ISSUE THREAD

**Issue by rs-mobitech** [roubachof/Sharpnado.MaterialFrame#10]
Hi, With iOS when frames (for example in Silly App) display for the first time, there is a flash of white that displays in each frame. Any idea on what's causing this?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39233783/88032268-adc36800-cb78-11ea-9aa1-e19ede7a3d7f.gif)

**Comment by rs-mobitech** [comment]
Hello, any update yet?  I would really like to use your frames but the white flash appearing for a second in the frames is a problem for me so I cannot use them right now.  Thanks

**Comment by roubachof** [comment]
Nope, no news, don't have time for now. But I welcome any PR 👍 
It's all in the https://github.com/roubachof/Sharpnado.MaterialFrame/blob/master/MaterialFrame/MaterialFrame.iOS/iOSMaterialFrameRenderer.cs file. I guess the `LayoutSubviews` method is called a bit too late...

**Comment by rs-mobitech** [comment]
Thanks, sorry but my skills are not up to yours as far as understanding what is happening.

**Comment by roubachof** [comment]
unfortunately, I cannot make the flash go away (anyway in the HorizontalListView, didn't test it in other list view like CollectionView).
It seems to occur when using Sharpnado Tabs + UICollectionView

**Comment by roubachof** [comment]
Ok, found it. By default all changes on CALayers are animated, just had to call RemoveAllAnimations() after setting the Frame:

```csharp
                _intermediateLayer.Frame = new CGRect(0, 2, Element.Width, Element.Height - 2);
                _intermediateLayer.RemoveAllAnimations();
```

**Comment by roubachof** [comment]
fixed by https://github.com/roubachof/Sharpnado.MaterialFrame/releases/tag/v1.1.3
