### ISSUE TITLE
Add an XMLNS Definition

### ISSUE THREAD

**Issue by dansiegel** [roubachof/Sharpnado.MaterialFrame#11]
**Is your feature request related to a problem? Please describe.**

Particularly as there is more than one Sharpnado package, any UI elements that would be referenced from XAML should be easily available with a single xmlns.

**Describe the solution you'd like**

```xml
<ContentPage xmlns:sharpnado="http://sharpnado.com">
  <sharpnado:MaterialFrame />
</ContentPage>
```

**Describe alternatives you've considered**

n/a

**Additional context**

Add a XmlnsDefinitionAttribute to all Sharpnado packages like:

```cs
[assembly: Xamarin.Forms.XmlnsDefinition("http://sharpnado.com", "Sharpnado.MaterialFrame")]
[assembly: Xamarin.Forms.XmlnsDefinition("http://sharpnado.com", "Sharpnado.AnotherClrNamespace")]
```

This helps to keep XAML cleaner particularly as you use an aggregate of types across your project as you do not have to remember which assembly something was in or what the clr namespace is.

**Comment by roubachof** [comment]
fixed by https://github.com/roubachof/Sharpnado.MaterialFrame/releases/tag/v1.1.3

**Comment by dansiegel** [comment]
great to see!
