### ISSUE TITLE
Is there a way to reduce the size of the top frame shadow and to change the color?

### ISSUE THREAD

**Issue by rs-mobitech** [roubachof/Sharpnado.MaterialFrame#12]
Here's an image that explains what I mean.  On the left half of the frame the white shadow area is normal height.  On the right side it's smaller.  Is there a way that I could change the height.  Also is there a way I can change the color of the top shadow?

<img width="592" alt="Screen Shot 2020-10-10 at 16 34 32" src="https://user-images.githubusercontent.com/39233783/95649082-c5c2dc00-0b16-11eb-89cc-edb0e605a364.png">

**Comment by roubachof** [comment]
You can set the AcrylicGlowColor property to change the color of the upper shadow.

For your issue, it’s weird I never saw that before. I will need a repro sample to understand what’s going on

**Comment by roubachof** [comment]
closed due tu inactivity
