### ISSUE TITLE
Acrylic Blur not working on IOS

### ISSUE THREAD

**Issue by Strypper** [roubachof/Sharpnado.MaterialFrame#14]
**Platform (please complete the following information):**
 - OS: IOS
 - Device: ALL IOS DEVICES
 - Xamarin.Forms: 4.8

**Describe the bug**
Acrylic Blur is not applied to IOS

**Comment by roubachof** [comment]
As stated in the docs you cannot switch dynamically from a not blurred theme to acrylic blur on iOS. Blur won't be applied. It only works statically

**Comment by Strypper** [comment]
how to set it statically ?

**Comment by roubachof** [comment]
MaterialTheme="AcrylicBlur"
