### ISSUE TITLE
White Shadow on Android BlurRadius

### ISSUE THREAD

**Issue by andre-laskawy** [roubachof/Sharpnado.MaterialFrame#15]
Using the Android Blur Radius, e.g. like this

            <materialFrame:MaterialFrame
                Padding="0"
                AndroidBlurRadius="20"
                MaterialBlurStyle="{DynamicResource DynamicBlurStyle}"
                MaterialTheme="AcrylicBlur" />

and then putting any white control on it (e.g. a White Button) results in a light white shadow around the control, I couldn't find any solution to get rid of the shadow:

![image](https://user-images.githubusercontent.com/16267227/100232867-3be59b80-2f29-11eb-9247-3720dd28c6db.png)

**Comment by roubachof** [comment]
Set the AndroidMaterialFrameRenderer.ThrowStopExceptionOnDraw to true

**Comment by andre-laskawy** [comment]
Nice, that worked! Can't debug with this flag on, but I can get around this with a compiler constant.

**Comment by roubachof** [comment]
https://github.com/roubachof/Sharpnado.MaterialFrame#androidmaterialframerendererthrowstopexceptionondraw

yup this is a xamarin.android issue, is should be fixed in 16.8 though according to https://github.com/xamarin/xamarin-android/issues/4548

**Comment by andre-laskawy** [comment]
ohh ... I really should start reading the documentation. Cheers :)
