### ISSUE TITLE
MaterialFrame with Xamarin.Forms 5.0

### ISSUE THREAD

**Issue by Stedy59** [roubachof/Sharpnado.MaterialFrame#16]
MaterialFrame is not drawing properly... all GradientDrawable objects are white.

**Comment by andre-laskawy** [comment]
Had the same problem, but only in debug mode. 
Setting the background color of the material frame to transparent fixed the problem for me.

**Comment by roubachof** [comment]
:) https://github.com/roubachof/Sharpnado.MaterialFrame#android-compatibility-issues

**Comment by roubachof** [comment]
could repro the issue, i'm on it.
