### ISSUE TITLE
IsClippedToBounds not working on iOS

### ISSUE THREAD

**Issue by tomh4** [roubachof/Sharpnado.MaterialFrame#19]
**Platform (please complete the following information):**
 - OS: [iOS]
 - Device: [iPhoneXR/iPhoneSimulator]
 - Sdk vervion: [iOS 14.5]
 - Xamarin.Forms: [5.0.0.2012]
 - Sharpnado.MaterialFrame: [1.1.4]

**Describe the bug**
When adding an image to a rounded MaterialFrame with IsClippedToBounds="True" the image is not clipped on iOS where everything works as expected on Android.

**To Reproduce**
-Add a MaterialFrame
-Set Padding to 0
-Add image inside

```
<effects:MaterialFrame Margin="12" HasShadow="True" Padding="0" 
                                    HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" 
                                    Grid.Row="0" Grid.Column="0" Elevation="20"
                                    CornerRadius="32" >
          <Image Aspect="AspectFill" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Source="{Binding CoverMedia}"/>
</effects:MaterialFrame>
```
**Screenshots (if applicable)**
Result:
![image](https://user-images.githubusercontent.com/19487549/121389930-2bd55c80-c94d-11eb-9222-0efe4273771f.png)
Expected Result:
![image](https://user-images.githubusercontent.com/19487549/121390007-3e4f9600-c94d-11eb-87df-e08e40981797.png)

**Comment by roubachof** [comment]
Cannot reproduce with material frame 1.2:

![image](https://user-images.githubusercontent.com/596903/138913154-5489532a-bcd0-4b53-803e-60208197c80a.png)

```xml
<rv:MaterialFrame Margin="12"
                              Padding="0"
                              HorizontalOptions="FillAndExpand"
                              VerticalOptions="FillAndExpand"
                              CornerRadius="32"
                              IsClippedToBounds="True">
    <Image Source="{images:ImageResource me.jpg}" />
</rv:MaterialFrame>
```

also, you forgot to set `IsClippedToBounds="True"` in your xaml :)
