### ISSUE TITLE
[Enhancement] Dark Acrylic(Dark Neumorphism)

### ISSUE THREAD

**Issue by mhrastegari** [roubachof/Sharpnado.MaterialFrame#2]
## Summary
i think it's needed when the application is in Dark mode.
imagin someone designed its app Neumorphism like and switched to dark mode! the only way for that app is turn to the Material flat Dark, well i did that with the new "OnApptheme" in X.F 4.6.

## Example ScreenShot
![Dark_Acrylic](https://user-images.githubusercontent.com/42671084/80796165-c2b0e080-8bb3-11ea-94e0-6f18cc18c29c.png)

Skeuomorphic/Neumorphism Timer apps Dark mode
by Alkhl Studio

https://dribbble.com/shots/9410478-Skeuomorphic-Neumorphism-Timer-apps-Dark-mode#shot-description

## Platforms
Core/Xaml (All Platforms)
UWP
iOS
Android
WPF

**Comment by roubachof** [comment]
You can implement this easily with classic XF Frame and  https://github.com/roubachof/Sharpnado.Shadows x)

**Comment by mhrastegari** [comment]
Awesome! Thanks ❤
