### ISSUE TITLE
[macOS/UWP] BehindWindow and HostBackdrop

### ISSUE THREAD

**Issue by mhrastegari** [roubachof/Sharpnado.MaterialFrame#20]
## Description
Could we have a nice Background acrylic for desktop?
Background acrylic reveals the desktop wallpaper and other windows that are behind the currently active app.
## ScreenShot
![image](https://user-images.githubusercontent.com/42671084/121815899-e20eae00-cc8d-11eb-9e5c-0b64c52008c2.png)

**Comment by roubachof** [comment]
Yup we could.
If you make a PR :))

**Comment by mhrastegari** [comment]
Hi @roubachof I think I figured out something for UWP 🤔

Just not sure about it (one of the reasons is it's gonna be my second ever public PR) but I tried in my [little project](https://github.com/mhrastegary77/Xamsta) and it worked.

**Comment by roubachof** [comment]
I think it should be a specific UWP option (and maybe also macOS) because it could change the semantic of view. Something like bool UWPHostBackdropBlur

**Comment by mhrastegary77** [comment]
i don't know i did it right or not but could you look at the last commit i pushed?

**Comment by mhrastegari** [comment]
I just added platform specific options for both macOS and UWP.
