### ISSUE TITLE
Can't click in new page

### ISSUE THREAD

**Issue by mGameStudio** [roubachof/Sharpnado.MaterialFrame#26]
**Platform (please complete the following information):**
 - OS: [iOS/Android/Both]
 - Device: [iPhone6/iPhoneSimulator/Pixel/AndroidEmulator/...]
 - Sdk vervion: [iOS 15/Android SDK 28]
 - Xamarin.Forms: [5.0.0.233]

**Describe the bug**
set a materialframe theme to AcrylicBlur,navigate to next page,only top left corner can click,if set materialTheme to Acrylic,everything is ok.

**To Reproduce**
1. set MainPage as NavigationPage
2. Create a Page A and contain a MaterialFrame,set MaterialTheme to AcrylicBlur
3. Create a Page B,set MaterialTheme to AcrylicBlur,add a button and PushAysnc to a new PageB
4. Page A navigate to Page B,Page B navigate to Page B 
5. The new Page B can't click it,If set MaterialTheme to Acrylic ,it will navigate to Page B forever.

**Exceptions (if applicable)**
no error or exception
```
Unhandled Exception:
no error or exception
```

**Screenshots (if applicable)**
I create a new project to reproduce it.

https://drive.google.com/file/d/10mrigKeh4OjKPXv9AqMa4lgRJACqJ02w/view?usp=sharing

**Comment by roubachof** [comment]
Not applicable anymore
