### ISSUE TITLE
How to set the blur color?

### ISSUE THREAD

**Issue by Syed-RI** [roubachof/Sharpnado.MaterialFrame#27]
Lets say instead of out of box black and white I wanted to apply a pink blur. How do I go about doing that in MAUI?

**Comment by roubachof** [comment]
You can use the android and winui specific properties:

AndroidBlurOverlayColor and WinUIBlurOverlayColor

the ios api doesn't support this

**Comment by Syed-RI** [comment]
Thanks @roubachof ! Here is an promising alternative with said feature (TintColor): https://github.com/sswi/AcrylicView.MAUI

**Comment by roubachof** [comment]
Ahah I saw that he just took the android implementation from this repo !
But he mentioned it in the read me so it's fine
