### ISSUE TITLE
Failed to resolve assembly: 'Sharpnado.MaterialFrame.Maui

### ISSUE THREAD

**Issue by mjosipovic-tgr** [roubachof/Sharpnado.MaterialFrame#28]
**Platform (please complete the following information):**
 - OS: [Both]
 - Device: [ALL]
 - Sdk vervion: [iOS 11/Android SDK 21]
 - .NET MAUI

**Describe the bug**
I added the nuget package, referenced it in MauiProgram, but it keeps failing the build with Failed to resolve assembly: 'Sharpnado.MaterialFrame.Maui, in csproj there is a reference to a version 2.0.0

**Exceptions (if applicable)**
XamlC error : Failed to resolve assembly: 'Sharpnado.MaterialFrame.Maui, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by roubachof** [comment]
This is just a visual studio issue clean the project bin/obj folders
