### ISSUE TITLE
Any plans to add a dark mode to Material Frame?

### ISSUE THREAD

**Issue by rs-mobitech** [roubachof/Sharpnado.MaterialFrame#8]
I would love to be able to use your material frame but I don't see any way to have a dark mode with dark colored frames on a dark background and a small shadow around the frame.  Do you have any plans or suggestions on how to add this?  From what I see all of your dark frame examples still appear on a light colored background.

**Comment by roubachof** [comment]
Mmmh I’m afraid I don’t understand your question... The dark mode supports the black elevation from the material design. I don’t understand what a dark colored frame is.

**Comment by rs-mobitech** [comment]
Thanks for your very quick reply.  I just now created this image to show you what my application looks like.  I believe your theme would be a great fit for the light themed version of my app (with some changes to the colors to make them the same as you use),  but I am not sure how to use your theme for the dark colored image.  Note that I'm very flexible to make changes to the frame and background color as right now I'm not very happy with my own choice of colors and much prefer your choice of colors you use for the light color theme. 

<img width="367" alt="Screen Shot 2020-07-19 at 18 08 22" src="https://user-images.githubusercontent.com/39233783/87871439-2e545e00-c9eb-11ea-87aa-1637432ed040.png">

**Comment by roubachof** [comment]
I don’t think you need anything more than a regular frame with rounded corner. Just use DynamicResource instead of StaticResource and you’ll be good to go: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/theming
